version: '3.8'

services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-end/src:/app/src
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./back-end/src:/app
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
